apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - otel-collector-config.yaml
  - otel-collector.yaml
  - prometheus-config.yaml
  - prometheus.yaml

