apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-runner

resources:
  - serviceaccount.yaml
  - runner-secret.yaml
  - kubeconfig-configmap.yaml
  - deployment.yaml

