apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monorepo-routes
  namespace: gateway
spec:
  parentRefs:
    - name: monorepo-gateway
      namespace: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /go
      backendRefs:
        - name: go-service
          namespace: go-app
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /node
      backendRefs:
        - name: node-service
          namespace: node-app
          port: 80

