apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CRD stable: GatewayClass, Gateway, HTTPRoute, etc
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml

