apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: node-app
spec:
  template:
    spec:
      containers:
        - name: node-service
          image: monorepo/node-service:local

