apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-service
          image: monorepo/node-service:dev
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_SERVICE_NAME
              value: node-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"

