apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOURUSER/YOURREPO.git'
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: go-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

