apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: go-app
spec:
  template:
    spec:
      containers:
        - name: go-service
          image: monorepo/go-service:local

