apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: go-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-apps
spec:
  selector:
    app: go-service
  ports:
    - port: 80
      targetPort: 8080

