apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-go.yaml
  - ns-node.yaml
  - ns-observability.yaml
  - go-deployment.yaml
  - node-deployment.yaml
  - otel-collector-config.yaml
  - otel-collector-deployment.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml

